# Generated by Django 4.1.7 on 2023-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0002_remove_firealert_completed_remove_firealert_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealert',
            name='img',
            field=models.CharField(max_length=180),
        ),
    ]
