# Generated by Django 4.1.7 on 2023-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0003_alter_firealert_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAlertExpoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_token', models.CharField(max_length=300)),
            ],
        ),
    ]
