# Generated by Django 4.1.7 on 2023-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.TimeField(auto_now=True, verbose_name=''),
        ),
    ]
